### ISSUE TITLE
missing call dependencies.

### ISSUE THREAD

**Issue by luckiboy** [xjtu-enre/ENRE-cpp#5]
# Missing Call Dependencies Bug Report

## Known Test Cases

1. **Function Continuous Call**
2. **Try Catch Exception**
3. **Throw Exception**
4. **Template Struct Extend**
5. **Variable to Variable Flow**
6. **Struct Class Friends**
7. **Increment Modify**
8. **One's Compliment Modify**
9. **Increment Deref Modify**
10. **Deref Set**

### 1. Specific Code

```cpp
int funcA(){
    return -1;
}
int funcB(int i){
    return 0;
}
void run_benchmark(){
    funcB(funcA());
}
```

### 2. Current Tool Generated Result

```yaml
name: Function Continuous Call
relation:
    type: Calls
    items:   
    -   from: Function:'run_benchmark'
        to: Function:'funcB'
        loc: file0:8:5
```

### 3. Target Generated Result

```yaml
name: Function Continuous Call
relation:
    type: Calls
    items:
    -   from: Function:'run_benchmark'
        to: Function:'funcA'
        loc: file0:8:11
    -   from: Function:'run_benchmark'
        to: Function:'funcB'
        loc: file0:8:5
```

### 4. Description

**The content of the Missing Call Dependencies Bug Report section shows that the current tool generated result is missing. The Current Tool Generated Result and Target Generated Result represent the current tool generated result and the target generated result respectively. It is obvious that the Current Tool Generated Result is missing a dependency compared to the Target Generated Result.**
