### ISSUE TITLE
Result redundancy.

### ISSUE THREAD

**Issue by luckiboy** [xjtu-enre/ENRE-cpp#6]
# Result redundancy Bug Report

## Known Test Cases

1. **File Declares Function**

### Specific Code

```cpp
#include <iostream>

void greet();

void greet() {
    std::cout << "Hello, World!" << std::endl;
}
```
### Current Tool Generated Result

```yaml
name: File Declares Function
relation:
  type: Declares
  items:
    -   from: File:'myFunction'
        to: Function:'greet'
        loc: file0:3:6
    -   from: File:'myFunction'
        to: Function:'greet'
        loc: file0:3:6
```

### Target Generated Result

```yaml
name: File Declares Function
relation:
  type: Declares
  items:
    -   from: File:'myFunction'
        to: Function:'greet'
        loc: file0:3:6
```

### Description

**The Result redundancy Bug Report indicates that the tool extracted the same dependency twice or more times, resulting in redundancy.**
