### ISSUE TITLE
Dependencies missing due to the absence of entities

### ISSUE THREAD

**Issue by luckiboy** [xjtu-enre/ENRE-cpp#7]
# Dependencies missing due to the absence of entities Bug Report

## Known Test Cases

1. **Dreref call**

### Specific Code

```cpp
void run_benchmark(void (*setup)(void*), void* data) {
    int i;
    for (i = 0; i < count; i++) {
        if (setup != NULL) {
            setup(data);
        }
    }
}
```
### Current Tool Generated Result

```yaml
# Dependency does not exist
# setup is a function pointer that points to a function which takes a parameter of type void* and returns void.
```

### Target Tool Generated Result

```yaml
name: Deref Call
relation:
    type: Call
    items:
    - from: Function:'run_benchmark'
      to: Variable:'setup'
      loc: file0:5:13
```

### Description
**Dependencies missing due to the absence of entities Bug Report This part indicates that the dependencies related to the entity cannot be successfully extracted because the tool failed to successfully extract the entity.**
