### ISSUE TITLE
The result is missing certain dependencies

### ISSUE THREAD

**Issue by luckiboy** [xjtu-enre/ENRE-cpp#8]
# The result contains only reads, without any calls relationship Bug Report

## Known Test Cases

1. **Method function call**

### Specific Code

```cpp
class dog
{
public:
   void setAge(int age)     
   {
      _age = age;
   }
private:
   int _age;
};
int main()
{
   dog mongrel;
   mongrel.setAge(5);
}
```
### Current Tool Generated Result

```yaml
name: Method Function Call
relation:
    type: Reads
    items:
    - from: Function:'run_benchmark'
      to: Function:'dog::setAge'
      loc: file0:14:12
```

### Target Tool Generated Result

```yaml
name: Method Function Call
relation:
  type: Calls
  items:
    -   from: Function:'main'
        to: Function:'dog::setAge'
        loc: file0:14:12
```

### Description

**The result contains only reads, without any calls relationship Bug Report shows an extraction error. The tool failed to identify a call dependency and only identified the reads dependency.**
