### ISSUE TITLE
Improper handling of pointer access

### ISSUE THREAD

**Issue by luckiboy** [xjtu-enre/ENRE-cpp#9]
# Improper handling of pointer access

### Specific Code
```cpp
// Assuming CalculatorManagerDisplayTester and necessary headers are already defined
class CalculatorManagerDisplayTester {
public:
    int GetMaxDigitsCalledCount() {
        return m_maxDigitsCalledCount;
    }

private:
    int m_maxDigitsCalledCount = 0;
};

void TestMaxDigitsReachedScenario(const wstring& constInput) {
    CalculatorManagerDisplayTester* pCalculatorDisplay = (CalculatorManagerDisplayTester*)m_calculatorDisplayTester.get();

    // Make sure we're in a clean state.
    VERIFY_ARE_EQUAL(0, pCalculatorDisplay->GetMaxDigitsCalledCount());

    vector<Command> commands;
    VERIFY_IS_FALSE(commands.empty());

    // The last element in the list should always cause MaxDigitsReached
    // Remember the command but remove from the actual input that is sent
    Command finalInput = commands[commands.size() - 1];
    commands.pop_back();

    wstring input = constInput.substr(0, constInput.length() - 1);

    // Additional logic for TestMaxDigitsReachedScenario can go here
}
```

### Current Tool Generated Result
```yaml
# Dependency does not exist
```

### Target Tool Generated Result
```yaml
name: Max Digits Call
relation:
    type: Call
    items:
    - from: Function:'TestMaxDigitsReachedScenario'
      to: Function:'CalculatorManagerDisplayTester::GetMaxDigitsCalledCount'
      loc: file0:16:44
```

### Description

**The Improper handling of pointer access section indicates that the access dependency of the pointer part cannot be extracted successfully.**
